package mio68.lab.tryit.puzzlers;

import java.io.IOException;

public class Puzzle37_Arcane2 {
    public static void main(String[] args) {
        try {
            // It compiles just OK! Why?
        } catch (Exception e) {
            System.out.println("This can't happen!");
        }
    }
}
